# Python libraries for data science


# An introduction to numpy




In [ ]:
#if we cannot import, we need to install
#to install packets we use pip install xxxxx


#!pip install numpy


In [1]:
import numpy as np

## How to create numpy arrays

### Option 1. From a python list


In [2]:
fibonacci_sequence = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811]


In [3]:
fibonacci_sequence

[0,
 1,
 1,
 2,
 3,
 5,
 8,
 13,
 21,
 34,
 55,
 89,
 144,
 233,
 377,
 610,
 987,
 1597,
 2584,
 4181,
 6765,
 10946,
 17711,
 28657,
 46368,
 75025,
 121393,
 196418,
 317811]

In [4]:
type(fibonacci_sequence)

list

In [5]:
np_fibonacci = np.array(fibonacci_sequence)

In [6]:
np_fibonacci

array([     0,      1,      1,      2,      3,      5,      8,     13,
           21,     34,     55,     89,    144,    233,    377,    610,
          987,   1597,   2584,   4181,   6765,  10946,  17711,  28657,
        46368,  75025, 121393, 196418, 317811])

In [7]:
type (np_fibonacci)

numpy.ndarray

As we can see both arrays look quite similar, we just imported a python list with the module function np (numpy alias is np) and then its function called array

Only way to differentiate one from the other is we get an array string next to the output of the numpy array

### Option 2. Using a method embedded in numpy's module


In [8]:
numpy_100 = np.arange(100)
numpy_100

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

Very similar to the range function we saw in python's native functions. We can also specify the jump and the start and finish with a slightly different syntax

In [9]:
numpy_100_pairs = np.arange(0,100,2)
numpy_100_pairs

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [10]:
numpy_0= np.zeros(5)
numpy_0

array([0., 0., 0., 0., 0.])

### Option 3. Manually

In [11]:
#just use np.array and then, remember you are calling a module's function so after the parenthesis use [ ]
my_array = np.array([6,2,43,1,2,43,6,7,45,23])
my_array

array([ 6,  2, 43,  1,  2, 43,  6,  7, 45, 23])

# Dimensionality in numpy arrays

So far we are only creating numpy arrays of one dimension or rank 1

In [ ]:
#Let's take last array and convert it to two dimensions

In [12]:
a = my_array.reshape(2,5)

We want two rows and 5 columns in this new dispossition

In [13]:
a

array([[ 6,  2, 43,  1,  2],
       [43,  6,  7, 45, 23]])

In [14]:
print(a.ndim)
#number of dimensions

2


In [15]:
#what if you want to select an element by index?
a[1,3]

45

Remember python starts counting at 0, we have selected row 2 element 4
If we try to do the reshape with a non multiple vairant we will get a Value error so watch out!

In [16]:
b = my_array.reshape(3,3)

ValueError: ignored

In [ ]:
#we cannot make an array because it is not multiple of 3

In [17]:
array_c = np.array([1,2,3,4,2,1,2,343,4,3,12,2])

In [18]:
c = array_c.reshape(3,4,1)
c

array([[[  1],
        [  2],
        [  3],
        [  4]],

       [[  2],
        [  1],
        [  2],
        [343]],

       [[  4],
        [  3],
        [ 12],
        [  2]]])

In [19]:
#These commands will give us the size, shape and dimensions of the array 
print(c.size)
#the length of the array, number of elements

12


In [20]:
print(c.shape) 
#matches the reshape command we just did

(3, 4, 1)


In [21]:
print(c.ndim)
#number of dimensions

3


In [22]:
d = [[0,1,2,3],[4,5,6],[7,8,9]]

In [24]:
d = np.array(c)
d

array([[[  1],
        [  2],
        [  3],
        [  4]],

       [[  2],
        [  1],
        [  2],
        [343]],

       [[  4],
        [  3],
        [ 12],
        [  2]]])

## Arithmetical operations

In [25]:
my_array_plus_one = my_array + 1

In [26]:
my_array_plus_one

array([ 7,  3, 44,  2,  3, 44,  7,  8, 46, 24])

In [27]:
my_array_times_five = my_array * 5

In [28]:
my_array_times_five

array([ 30,  10, 215,   5,  10, 215,  30,  35, 225, 115])

# Statistical operations

Let's take the fiubonacci sequence created before and find how much are all values inside

In [29]:
np_fibonacci.sum()
#sum of elements

832039

In [30]:
np_fibonacci.mean()
#average of elements

28691.0

In [31]:
var_fibonacci = np_fibonacci.var()
var_fibonacci

4812262130.0

In [32]:
np_fibonacci.var()
#gives variance

4812262130.0

In [33]:
np.sort(my_array)
#ascend order

array([ 1,  2,  2,  6,  6,  7, 23, 43, 43, 45])

In [34]:
-np.sort (-my_array)
#reverse order

array([45, 43, 43, 23,  7,  6,  6,  2,  2,  1])

# Making matrixes

In [35]:
#numpy has some algebra structures already implemented, all you need to do is call a function
identity_matrix = np.identity(5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Loading data into numpy from a file

Import first data_samples in collab, in github repo! 

https://github.com/Callisthenes/python_course_ie

In [ ]:
exercises = np.genfromtxt('data_sample.txt', delimiter=',')
exercises

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

Try to index some values!


In [ ]:
exercises[2:4, 0:2]

array([[11., 12.],
       [16., 17.]])

# Pandas

In [36]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("Global_annual_population.csv")

In [ ]:
df.head()

Year   Population  Unnamed: 2
0  1960         3.03         NaN
1  1961         3.07         NaN
2  1962         3.12         NaN
3  1963         3.19         NaN
4  1964         3.26         NaN

In [ ]:
df.describe()

Year   Population  Unnamed: 2
count    62.000000    62.000000         0.0
mean   1990.500000     5.341774         NaN
std      18.041619     1.457241         NaN
min    1960.000000     3.030000         NaN
25%    1975.250000     4.080000         NaN
50%    1990.500000     5.325000         NaN
75%    2005.750000     6.570000         NaN
max    2021.000000     7.840000         NaN

In [ ]:
df.value_counts()

Series([], dtype: int64)

In [ ]:
df.columns

Index(['Year', ' Population', 'Unnamed: 2'], dtype='object')

In [ ]:
print(df["Year"])

0     1960
1     1961
2     1962
3     1963
4     1964
      ... 
57    2017
58    2018
59    2019
60    2020
61    2021
Name: Year, Length: 62, dtype: int64


In [ ]:
print(df.iloc[20:40, :2])

    Year   Population
20  1980         4.43
21  1981         4.51
22  1982         4.59
23  1983         4.67
24  1984         4.76
25  1985         4.84
26  1986         4.92
27  1987         5.01
28  1988         5.10
29  1989         5.19
30  1990         5.28
31  1991         5.37
32  1992         5.45
33  1993         5.54
34  1994         5.62
35  1995         5.71
36  1996         5.79
37  1997         5.87
38  1998         5.95
39  1999         6.03


In [ ]:
pd.set_option()